# Generated by Django 3.2.5 on 2021-07-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stopwatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solve',
            name='scramble',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
